### ISSUE TITLE
Handle tables' prefixes

### ISSUE THREAD

**Issue by uznog** [mpchadwick/dbanon#13]
First of all, thanks for this great project!

I'd like to ask whether you're planning to handle databases with prefixes at any time in the future and/or you accept PRs in this matter?

Cheers!

**Comment by mpchadwick** [comment]
Sorry for not responding. I'm just noticing this issue has been open. In the case of table prefixes (I'm assuming you mean the Magento table prefix feature) I'd recommend using a custom config file. It should be fairly easy to take the existing bundled Magento 2 config file, but update the table names to include the prefixes.
